#!/bin/sh

# PROVIDE: bdautostart
# REQUIRE: DAEMON
# KEYWORD: nojail

. /etc/rc.subr

name="bdautostart"
desc="Run bd's 'autostart' command"
rcvar="bdautostart_enable"
stop_cmd=":"
start_cmd="/usr/local/bin/bd autostart"

load_rc_config $name

# doesn't make sense to run in a svcj: privileged operations
bdautostart_svcj="NO"

run_rc_command "$1"
